# generated by datamodel-codegen:
#   filename:  config-schema.json

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class ModelDescriptor(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    createdAt: AwareDatetime | None = None
    authors: list[str] | None = None
    family: str | None = None
    name: str | None = Field(None, min_length=1)
    docURL: str | None = None
    sourceURL: str | None = None
    datasetsURL: list[str] | None = None
    version: str | None = None
    revision: str | None = None
    vendor: str | None = None
    licenses: list[str] | None = None
    title: str | None = None
    description: str | None = None


class ModelFS(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["layers"]
    diffIds: list[str] = Field(..., min_length=1)


class Language(RootModel[str]):
    root: str = Field(..., pattern="^[a-z]{2}$")


class Modality(
    RootModel[Literal["text", "image", "audio", "video", "embedding", "other"]]
):
    root: Literal["text", "image", "audio", "video", "embedding", "other"]


class ModelCapabilities(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    inputTypes: list[Modality] | None = None
    outputTypes: list[Modality] | None = None
    knowledgeCutoff: AwareDatetime | None = None
    reasoning: bool | None = None
    toolUsage: bool | None = None
    reward: bool | None = None
    languages: list[Language] | None = None


class ModelConfig(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    architecture: str | None = None
    format: str | None = None
    paramSize: str | None = None
    precision: str | None = None
    quantization: str | None = None
    capabilities: ModelCapabilities | None = None


class Model(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    descriptor: ModelDescriptor
    modelfs: ModelFS
    config: ModelConfig
